### ISSUE TITLE
Gutenberg: Predefined Font Sizes

### ISSUE THREAD

**Issue by bgardner** [studiopress/genesis-sample#106]
Currently the Gutenberg editor allows users to specify text sizes: S, M, L, XL

As discussed [here](https://github.com/WordPress/gutenberg/pull/5269), similar to theme colors, it would be great if themes could set those sizes.

Worth nothing that classes are output for each option:

.is-small-text {}
.is-medium-text {}
.is-large-text {}
.is-larger-text {}

If custom font size is used, output is inline style.

**Comment by samikeijonen** [comment]
I still see this issue.

- Add new paragraph block.
- Set Custom Size to `L`.
- It adds inline style `style="font-size: 36px;"`.

What it should do is add class `is-large-text` so that it would respect what theme wants.

In Core block there happens to be the same font sizes:)

```css
p {
	&.is-small-text {
		font-size: 14px;
	}

	&.is-regular-text {
		font-size: 16px;
	}

	&.is-large-text {
		font-size: 36px;
	}

	&.is-larger-text {
		font-size: 48px;
	}
}
```

cc: @mtias @jasmussen
