### ISSUE TITLE
Gutenberg: review mobile block layout

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#117]
Noting we'll need to adjust this:

```css
.full-width-content .entry-content .alignwide {
	margin-left: -180px;
	margin-right: -180px;
	max-width: 1080px;
}
```

Which is currently causing the width to overflow the screen for smaller screen widths at https://demo.studiopress.com/genesis-sample-beta/:

<img width="905" alt="genesis_framework_ _supports_html5___responsive_design" src="https://user-images.githubusercontent.com/647669/45873567-167e0580-bd93-11e8-8399-d09690e9d09c.png">

To make it mobile-first, we can remove the negative margin left/right and max-width rules and adjust content for a single column by default, then add the negative margin and max-width overrides for larger widths via `@media only screen and (min-width: …`.
