### ISSUE TITLE
Remove style-editor-title.css once Gutenberg specificity issues are fixed

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#125]
Gutenberg functionality was merged in https://github.com/studiopress/genesis-sample/pull/121 in a single folder at `lib/gutenberg`.

Currently, editor styles for the post title live in their own file at `lib/gutenberg/style-editor-title.css` due to specificity issues with Gutenberg editor styles that prevent it being styled via `style-editor.css`.

This issue is a reminder to adapt and move those styles into `lib/gutenberg/style-editor.css` once these issues in Gutenberg are resolved (hopefully before WP 5.0 lands):

- https://github.com/WordPress/gutenberg/issues/10485
- https://github.com/WordPress/gutenberg/issues/10067

The title styling currently looks like this:

```CSS
.editor-post-title__block .editor-post-title__input {
    font-family: 'Source Sans Pro', sans-serif;
    font-size: 30px;
    font-weight: 400;
    line-height: 1.2;
    margin: 0 0 20px;
}
```

It will need to be changed to this and be moved to style-editor.css once the above issues are solved:

```CSS
body .editor-post-title__block .editor-post-title__input {
    font-family: 'Source Sans Pro', sans-serif;
    font-size: 30px;
    font-weight: 400;
    line-height: 1.2;
    margin: 0 0 20px;
}
```

The extra admin stylesheet at `lib/gutenberg/style-editor-title.css` can then be removed and the `require` line removed from `lib/gutenberg/init.php`.
