### ISSUE TITLE
Content is cut off with alignwide blocks

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#166]
Content is cut off with alignwide blocks, so the content is currently cut off with the homepage blocks.

It is more obvious in Windows browsers due to scrollbar width.

![texthidden](https://user-images.githubusercontent.com/1271053/50362693-aa986e00-0536-11e9-81ed-ff301b316fe3.png)

Updating the media query in `front-end.css` as below will eliminate the cut off text, though it will bu directly against the scrollbar.

```css
@media only screen and (min-width: 1109px) {

	.full-width-content .entry-content .alignwide {
		margin-left: -180px;
		margin-right: -180px;
		min-width: 1062px;
	}

}
```
![fix2 png](https://user-images.githubusercontent.com/1271053/50363039-1af3bf00-0538-11e9-97e6-654812f60599.PNG)

That accounts for 1062px + 17px scrollbar width + 30px for the padding on the .site-inner left that shifts everthing to the right slightly.

However, I think it is better as 1062px + 17px scrollbar width + 60px for the padding on the .site-inner so it balances out right to left.

```css
@media only screen and (min-width: 1139px) {

	.full-width-content .entry-content .alignwide {
		margin-left: -180px;
		margin-right: -180px;
		min-width: 1062px;
	}

}
```

Edited to add that this works better across more widths:
```css
@media only screen and (min-width: 960px) {

	.full-width-content .entry-content .alignwide {
		margin-left: -180px;
		margin-right: -180px;
		max-width: 1062px;
	}

}
```

I've not yet looked at editor styles.
