### ISSUE TITLE
is-style-outline button hover color

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#173]
In gutenberg `front-end.css` the button used in the homepage contact section with a class of `is-style-outline` is styled with theme blue here:

```css
.content .wp-block-button.is-style-outline .wp-block-button__link:focus,
.content .wp-block-button.is-style-outline .wp-block-button__link:hover {
	color: #0073e5;
}
```

However, it doesn't pick up the custom colors. In addition, it is not an accessible color against the dark background.
