### ISSUE TITLE
Sticky header and page jumping anchor links

### ISSUE THREAD

**Issue by waybis** [studiopress/genesis-sample#269]
If you have a table of contents or anchor links on a page, the sticky header covers the anchor after jumping.

**Comment by nickcernis** [comment]
A potential pure-CSS fix for this is:

```CSS
@media only screen and (min-width: 960px) {
	:target:before {
		content:"";
		display: block;
		height: 70px;
		margin: -70px 0 0;
	}
}
```

But this will need further testing to check for side-effects.
