### ISSUE TITLE
Gutenberg: adding wide blocks causes horizontal scroll bars

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#91]
Making any block a wide one causes horizontal scroll bars to appear in Firefox and Chrome on Mac at larger screen widths:

![wide-image-gutenberg](https://user-images.githubusercontent.com/647669/37039626-3f5a4dba-2158-11e8-9d33-f0c10152ed40.png)

![wide-image-horizontal-scroll-bars](https://user-images.githubusercontent.com/647669/37039636-424fa5c4-2158-11e8-82c3-634d0986648f.png)

It seems that the default Gutenberg styling uses `vw` units:

```CSS
	.full-width-content .alignfull {
		margin-left: calc(50% - 50vw);
		margin-right: calc(50% - 50vw);
	}
```

This causes Firefox and Chrome to use the full width ignoring the scroll bar, making a horizontal scroll bar appear. The main issue other than the scroll bar is that it affects legibility of text in full-width blocks (text on the left is cut off):

![lorem-ipsum-fallout](https://user-images.githubusercontent.com/647669/37040011-2300f5fa-2159-11e8-9b5e-d99922f16698.png)

Possible solutions:

1. Ignoring it.
2. The nuclear option: `overflow-x: hidden;` on the body.
3. Overriding with our own styles (would then not be quite full-width):
    ```CSS
	.full-width-content .alignfull {
		margin-left: calc(50% - 49vw);
		margin-right: calc(50% - 49vw);
	}
    ```
4. Using the approach proposed here: http://moc.co/2018/02/gutenberg-and-themes/
